env: hello
webserver:
  port: 8080
  prefix: /k8s-micro/v0
randomThread:
  sleepTime: 1s
app:
  threadSleep: 1s
kafkaProcessorConfig:
  hostUrl: http://localhost:9092
  readTopic: red
  writeTopic: green
  schemaRegistry:
      hostUrl: http://localhost:8081
      checkDuration: 60s
