env: hello
webserver:
  port: 8080
  prefix: /k8s-micro/v0
randomThread:
  sleepTime: 1s
app:
  threadSleep: 1s
kafkaProcessor:
  hostUrl: http://localhost:9092
  bootstrapServers: localhost:9092
  applicationId: k8s-micro-app
  processingGuarantee: exactly_once_v2
  autoOffsetReset: latest
  readTopic: input
  writeTopic: output
  taskSleepDuration: 10s
  querySleep: 15s
  schemaRegistry:
      hostUrl: http://localhost:8081
      checkDuration: 60s
sqlServer:
  database:
    url:  jdbc:postgresql://localhost:5432/mydatabase
    username: theboss
    password: ${secret_pw}
  driver: org.postgresql.Driver
  healthSleep: 60s
  threadSleep: 5s
